In [6]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 97,  87,  99,  77,  59],
       [ 67,  51,  64,  71,  62],
       [ 99,  88,  76,  51, 100],
       [ 66,  75,  64,  56,  69],
       [ 92,  72,  52,  92,  66],
       [ 99,  69,  99,  89,  94],
       [ 96,  68,  52,  60,  58],
       [ 50,  84,  68,  70,  62],
       [ 73,  61,  78,  98,  56],
       [ 53,  73,  94,  75,  70],
       [ 66,  93,  81,  66,  65],
       [ 64,  77,  62,  68,  95],
       [ 79,  50,  65,  83,  59],
       [ 50,  54,  82,  59,  63],
       [ 71,  95,  63,  64,  73],
       [ 70,  67,  88,  73,  51],
       [ 62,  93,  91,  82,  81],
       [ 58,  81,  54,  90,  97],
       [ 66,  63,  55,  99,  70],
       [ 62,  77,  93,  61,  67],
       [ 91,  87,  52,  80,  61],
       [ 79,  74,  63,  99,  51],
       [ 67,  83,  90,  59,  71],
       [ 98,  58,  94,  58,  70],
       [ 81,  90,  77,  86,  52],
       [ 70,  81,  85,  69,  80],
       [ 59,  80,  59,  96,  54],
       [ 82,  73,  60,  98,  83],
       [ 86,  78,  95,  85,  95],
       [ 85,  

In [7]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[ 95,  74,  72,  62,  63],
       [ 89,  52,  65,  53,  74],
       [ 94,  97,  56,  57,  63],
       [ 85,  65,  64,  88,  84],
       [ 96,  79, 100,  70,  62]])

In [8]:
students[:,0] #第一科所有分數
students[:,-1] #最後一科所有分數

array([ 59,  62, 100,  69,  66,  94,  58,  62,  56,  70,  65,  95,  59,
        63,  73,  51,  81,  97,  70,  67,  61,  51,  71,  70,  52,  80,
        54,  83,  95,  89,  83,  68,  74,  59,  95,  78,  96,  58,  65,
        77,  58,  87,  57,  90,  89,  63,  74,  63,  84,  62])

In [9]:
np.sum(students[:1]) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分 
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

array([76.5, 74.5, 72.5, 76. , 69.5])